---
# tasks file for ansible-role-backup-kvm_lvm
#

 - name: template in script
   template: src=kvm_lvm_backup.sh.j2 dest={{ backup_script_dest }} mode=0755
   when: backup_enabled and backup_vms != "" and backup_lvm != "" and backup_vg != ""
